// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMVC.Data;

namespace ProjetoMVC.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211127123010_Banco Inicial")]
    partial class BancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoMVC.Models.Comentarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEquipamentos")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipamentos");

                    b.HasIndex("IdPerfis");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("ProjetoMVC.Models.Equipamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("ProjetoMVC.Models.Perfis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Perfil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("ProjetoMVC.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPerfis")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfis");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoMVC.Models.Comentarios", b =>
                {
                    b.HasOne("ProjetoMVC.Models.Equipamentos", "Equipamentos")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdEquipamentos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoMVC.Models.Perfis", "Perfis")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdPerfis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamentos");

                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("ProjetoMVC.Models.Usuarios", b =>
                {
                    b.HasOne("ProjetoMVC.Models.Perfis", "Perfis")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("ProjetoMVC.Models.Equipamentos", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("ProjetoMVC.Models.Perfis", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
